### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/flutter_starter#11]
- [x] Add localization (#12)
- [x] Add theming (#14)
- [x] Add flutter_hooks and riverpod (#15)
- [x] Add services (#16)
- [x] Add mocking and testing (#25)
- [x] Switch from Make to Just (#19)
